# Custom Aliases
# j3rmbadger
alias vimconfig='nvim ~/.config/nvim/init.vim'
alias zshconfig='nvim ~/.zshrc'
alias aliasconfig='nvim ~/.oh-my-zsh/custom/aliases.zsh'
alias c='clear'
alias vi='nvim'
alias vim='nvim'
alias dirsize='du -d 1 -h'
alias cls='clear'
alias updategcp='gcloud components update'
alias get='sudo apt install -y'
alias update='sudo apt update && sudo apt dist-upgrade -y'
alias search='apt-cache search'
alias clean='sudo apt autoremove -y'
alias edit='sudo nvim'
